clean

diff --git a/.local/bin/remaps b/.local/bin/remaps
--- a/.local/bin/remaps
+++ b/.local/bin/remaps
@@ -3,36 +3,36 @@
 # LOGFILE="/home/flex/remaps.log"
 # echo "$(date) - remaps script started" >>$LOGFILE
 
-USER=$(logname 2>/dev/null)
-if [ -z "$USER" ]; then
-	USER=$(whoami)
-fi
+# USER=$(logname 2>/dev/null)
+# if [ -z "$USER" ]; then
+# 	USER=$(whoami)
+# fi
 # echo "$(date) - User: $USER" >>$LOGFILE
 
-if [ -z "$WAYLAND_DISPLAY" ]; then
-	echo "$(date) - Wayland display not found. Running Xorg commands" >>$LOGFILE
-	xset r rate 300 50 &
-	echo "$(date) - xset rate set" >>$LOGFILE
+# if [ -z "$WAYLAND_DISPLAY" ]; then
+# echo "$(date) - Wayland display not found. Running Xorg commands" >>$LOGFILE
+xset r rate 300 50 &
+# echo "$(date) - xset rate set" >>$LOGFILE
 
-	# pkill kanata
-	# echo "$(date) - kanata process killed" >>$LOGFILE
+# pkill kanata
+# echo "$(date) - kanata process killed" >>$LOGFILE
 
-	# Attempt to run kanata and capture any errors
-	# sudo -u $USER /home/$USER/.cargo/bin/kanata -c /home/$USER/.config/kanata/config.kbd >/dev/null 2>>$LOGFILE &
-	# if [ $? -eq 0 ]; then
-	# 	echo "$(date) - kanata started successfully" >>$LOGFILE
-	# else
-	# 	echo "$(date) - kanata failed to start. Check for errors above." >>$LOGFILE
-	# fi
+# Attempt to run kanata and capture any errors
+# sudo -u $USER /home/$USER/.cargo/bin/kanata -c /home/$USER/.config/kanata/config.kbd >/dev/null 2>>$LOGFILE &
+# if [ $? -eq 0 ]; then
+# 	echo "$(date) - kanata started successfully" >>$LOGFILE
+# else
+# 	echo "$(date) - kanata failed to start. Check for errors above." >>$LOGFILE
+# fi
 
-	[[ $(xinput --list | grep "TPPS/2 IBM TrackPoint") ]] && xinput --set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" -0.5 &
-	# echo "$(date) - IBM TrackPoint config set" >>$LOGFILE
+[[ $(xinput --list | grep "TPPS/2 IBM TrackPoint") ]] && xinput --set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" -0.5 &
+# echo "$(date) - IBM TrackPoint config set" >>$LOGFILE
 
-	[[ $(xinput --list | grep "TPPS/2 Elan TrackPoint") ]] && xinput --set-prop "TPPS/2 Elan TrackPoint" "libinput Accel Speed" -0.5 &
-	# echo "$(date) - Elan TrackPoint config set" >>$LOGFILE
+[[ $(xinput --list | grep "TPPS/2 Elan TrackPoint") ]] && xinput --set-prop "TPPS/2 Elan TrackPoint" "libinput Accel Speed" -0.5 &
+# echo "$(date) - Elan TrackPoint config set" >>$LOGFILE
 
-	[[ $(xinput --list | grep "SYNA800E:00 06CB:CE67 Touchpad") ]] && xinput --set-prop "SYNA800E:00 06CB:CE67 Touchpad" "libinput Tapping Enabled" 1 &
-	# echo "$(date) - Touchpad tapping enabled" >>$LOGFILE
-else
-	# echo "$(date) - Wayland display found, skipping Xorg commands" >>$LOGFILE
-fi
+[[ $(xinput --list | grep "SYNA800E:00 06CB:CE67 Touchpad") ]] && xinput --set-prop "SYNA800E:00 06CB:CE67 Touchpad" "libinput Tapping Enabled" 1 &
+# echo "$(date) - Touchpad tapping enabled" >>$LOGFILE
+# else
+# 	echo "$(date) - Wayland display found, skipping Xorg commands" >>$LOGFILE
+# fi
