"ChatGPT writing timer script that doesn't work"

diff --git a/.local/bin/timers b/.local/bin/timers
--- a/.local/bin/timers
+++ b/.local/bin/timers
@@ -1,31 +1,55 @@
 #!/bin/bash
 
-for ((i = 1; i <= $#; i++ )); do
-  # printf '%s\n' "Arg $i: ${!i}"
-	clear
-	notify-send "Starting timer #$i: ${!i}m"
-	hour=$(expr ${!i} / 60)
-	min=$(expr ${!i} % 60)
-	sec=0
-	while [ $hour -ge 0 ]; do
-		while [ $min -ge 0 ]; do
-			while [ $sec -ge 0 ]; do
-				echo -ne "Timer #$i (${!i}m): $hour:$min:$sec\033[0K\r"
-				let "sec=sec-1"
-				sleep 1
-			done
-			sec=59
-			if [ $min == 1 ]; then
-				notify-send "Last minute of timer #$i"
-			fi
-			let "min=min-1"
-		done
-		min=59
-		let "hour=hour-1"
-	done
-	# notify-send "Timer #$i ${!i}m done"
-	aplay ~/.local/bin/assets/bell02.wav &
-	clear
+# Check if at least one argument was provided
+if [ "$#" -lt 1 ]; then
+    echo "Usage: $0 <minutes>..."
+    exit 1
+fi
+
+# Check if necessary commands are available
+for cmd in aplay notify-send; do
+    if ! command -v $cmd &> /dev/null; then
+        echo "Error: $cmd is not installed."
+        exit 1
+    fi
 done
-notify-send "All timers done"
-aplay ~/.local/bin/assets/bell01.wav &
+
+clear
+
+total_timers=$#
+echo "Total number of timers: $total_timers"
+
+# For each argument
+for ((i=1; i<="$#"; i++)); do
+    timer=${!i}  # Get the value of the i-th argument
+    echo "Starting timer $i of $total_timers for $timer minutes."
+
+    # Count down
+    for ((j=timer*60; j>=0; j--)); do
+        mins=$((j/60))
+        secs=$((j%60))
+        clear
+        echo "Total number of timers: $total_timers"
+        echo -ne "Remaining on timer $i: ${mins}m ${secs}s\033[0K\r"
+
+        # If it's the final minute, send a notification
+        if [ $j -eq 60 ]; then
+            notify-send "Last minute of timer $i"
+        fi
+
+        # Don't sleep on the last second
+        if [ $j -gt 0 ]; then
+            sleep 1
+        fi
+    done
+
+    # Play the sound for the end of a timer
+    aplay ~/.local/bin/assets/bell02.wav &>/dev/null
+done
+
+# Play the sound for the end of all timers
+aplay ~/.local/bin/assets/bell01.wav &>/dev/null
+
+clear
+echo "Total number of timers: $total_timers"
+echo "All timers finished."
